### PR TITLE
chore: (PLATFORM-3528) update node version to 14LTS, update README

### PR DESCRIPTION
**Pull request by ovasdi**
https://artsyproduct.atlassian.net/browse/PLATFORM-3528

- bump Node version to 14LTS
- edit README

### CODE REVIEW

**Comment by ovasdi** [comment]
It seems that the [automated integration process](https://github.com/artsy/reaction#developing-in-force) with force has been removed. I tried running this and experienced the following: `Quicklink script not found at ../force/scripts/quicklink.sh, this project might not be compatible`. I wonder if [Developing in Force](https://github.com/artsy/reaction#developing-in-force) section should be removed then?

I've labeled this PR as `Trivial`, @icirellik should this be labeled differently?

**Review by icirellik — APPROVED** [review]
Looks great!

**Comment by icirellik** [comment]
I think it's fine to remove the "Developing in Force" section if it's no longer compatible. We can do so in another PR

**Comment by artsyit** [comment]
:rocket: PR was released in [`v29.3.0`](https://github.com/artsy/reaction/releases/tag/v29.3.0) :rocket:

**Pull request merged**
