### PR TITLE
[Collection] use filtered medium and time period list

### PR DESCRIPTION
**Pull request by artsyit**
Use only available list of mediums or time periods based on aggregations query for collections

screen shot 2018-10-22 at 1 20 22 pm

### CODE REVIEW

**Comment by eessex** [comment]
Is medium included in this pr? I'm guessing you'll need something like [this line](https://github.com/artsy/reaction/pull/1434/files#diff-cfadbe89b7889548a1c21979589aa7dcR13) after pulling most recent changes.

**Comment by artsyit** [comment]
@eessex the Medium filter is already hooked up to read from aggregations https://github.com/artsy/reaction/pull/1434/files#diff-f36b8724341cb92bce36b20d5478ec50R20

**Comment by l2succes** [comment]
oops. just realized I was logged into the @artsyit account lol

**Comment by eessex** [comment]
Ok just wanted to make sure this doesn't affect the mapping of filters in the medium component, worth  pulling the latest to double-check.

**Comment by xtina-starr** [comment]
@l2succes so you are the mysterious "artsyit" commenter 🤔

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 9ac6ec438c1b8e842b7b9b78334c5ff892738de1

https://deploy-preview-1434--artsy-reaction.netlify.com

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 9ac6ec438c1b8e842b7b9b78334c5ff892738de1

https://deploy-preview-1434--artsy-reaction.netlify.com

**Pull request merged**
