### PR TITLE
@alloy => FollowGeneButton

### PR DESCRIPTION
**Pull request by eessex**
Adds a button with mutations to follow a gene.

### CODE REVIEW

**Comment by alloy** [comment]
Looks good! 👍 

Future thought: we could probably make the follow button generic by adding a ‘followable’ interface to these types, because the button react components and relay code seem otherwise identical.

**Comment by alloy** [comment]
@eessex Let me know if you want to take a stab at that.

**Comment by eessex** [comment]
@alloy yes definitely-- was trying to find a way to reuse parts of the `handleFollow` but got tripped up by naming conventions for the queries.  Are there examples in the code now of this kind of interface?

**Comment by alloy** [comment]
Ah sorry, my comment was ambiguous. I was referring to a GraphQL interface. I.e. making it possible to use the same query for any ‘followable’ entity. I’ll write up a ticket with more details after dinner!

**Comment by alloy** [comment]
Consider the following schema:

```graphql
interface Favourable {
  __id: ID!
  id: ID!
  isFavourited: Boolean!
}

type Artist implements Favourable {
  # ...
}

type Artwork implements Favourable {
  # ...
}

type Gene implements Favourable {
  # ...
}

type Profile implements Favourable {
  # ...
}
```

By using an interface and stating that all these entities can be favourited, we have now make the act of favouriting an entity generic and so a favourite button would not need to know about the real type and can query like so:

```graphql
fragment FavouriteButton_favorable on Favourable {
  __id
  id
  isFavourited
}
```

Parent components would compose the fragment onto concrete types, e.g.:

```graphql
fragment ArtistFollowButton_artist on Artist {
  name
  ... FavouriteButton_favorable
}
```

…and a component that uses it like so:

```jsx
<FavouriteButton title={this.props.artist.name} favourable={this.props.artist} />
```

I have a working example that you can play with here https://launchpad.graphql.com/7llzqqx88j

Let me know if this is clear enough or whether we should jump on a call.

**Comment by alloy** [comment]
(Btw, the word ‘favourite’ is an example, I think these are all ‘collections’ in the core API, so maybe that’s the term we should use.)

**Pull request merged**
