### PR TITLE
Use the Palette CheckIcon

### PR DESCRIPTION
**Pull request by jonallured**
One in a series where I'm retiring SVGs in Reaction in favor of those in Palette for #2145. Here's the before/after:

## before
Screen Shot 2019-03-13 at 1 03 25 PM

## after
Screen Shot 2019-03-13 at 1 03 29 PM

The stroke of the checkmark looks a little too thin to my eye, but curious what @jeffreytr thinks!

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 1ac31bc260287791337599c2364f8720b723d8d6

https://deploy-preview-2157--artsy-reaction.netlify.com

**Comment by damassi** [comment]
@jonallured - mind reducing the size of the check somewhat? it's offcenter / brushing up against the right-hand size of the box. Should fit perfectly center. After that LGTM 👍 Merge when ready.

**Comment by jeffreytr** [comment]
+1 to what @damassi said regarding center alignment. The stroke weight looks fine to me, and matches the rest of the full icon set!

**Comment by jonallured** [comment]
Ok, took another pass at this and chatted with @jeffreytr on Slack to get design approval, here's how they look now:

Screen Shot 2019-03-15 at 10 54 30 AM

We opted for removing that legacy spacing but keeping the size at 18 since that's our standard icon size - ready for another review @damassi!! ❤️

**Comment by artsyit** [comment]
:rocket: PR was released in v15.5.2 :rocket:

**Pull request merged**
