### PR TITLE
[WIP] [Typings] Remove freeform system context props and improve Found typings

### PR DESCRIPTION
**Pull request by alloy**
Took this from #1524, as it doesn't need to be blocked by that PR.

(This is based on top of #1750, so that should be merged first.)

Also need to test if Force was relying on any of the Context symbols that got renamed.

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 80c31d26567cbae9726f8e610619182c8f2e867f

https://deploy-preview-1755--artsy-reaction.netlify.com

**Comment by damassi** [comment]
@alloy - Yup, there's a few areas in Force that use `ContextConsumer`.

**Comment by damassi** [comment]
@alloy - if there's any interest in completing this I can help carry it over the line if need be but with all of the changes this would probably be better closed and recreated, rather than rebased. Thoughts?

**Comment by alloy** [comment]
Yeah this should be recreated indeed :/ I do feel strongly about the change, so if it’s something you’d like to take on then that would be much appreciated.

https://artsyproduct.atlassian.net/browse/PLATFORM-1344

**Pull request closed without merging**
