### PR TITLE
@l2sucess => ErrorBoundaries in Display components

### PR DESCRIPTION
**Pull request by eessex**
Unfortunately prettier makes changes a little hard to see here...
One more PR related to articles showing no data -- https://sentry.io/artsynet/force-staging/issues/532264963/

- Wraps DisplayPanel component in ErrorBoundary
- Wraps DisplayCanvas component in ErrorBoundary
- Adds check if canvas has assets before searching for textmatch in url

### CODE REVIEW

**Comment by eessex** [comment]
ok to merge?

**Comment by kanaabe** [comment]
@eessex it looks like @l2succes  has a question above ^

**Comment by eessex** [comment]
@kanaabe we talked through this in person -- the error is handled in the error boundary component, and the check for the missing data has been added to the component.

**Comment by l2succes** [comment]
Yup! let's merge

**Pull request merged**
