### PR TITLE
[Lib] Bump react@16.13.0

### PR DESCRIPTION
**Pull request by damassi**
Bump to 16.13.0

### CODE REVIEW

**Comment by zephraph** [comment]
These test failures are weird: https://app.circleci.com/pipelines/github/artsy/reaction/9140/workflows/b542d1a5-5a85-4e87-9c2a-815e3f3d2c22/jobs/57610/tests

> Warning: unstable_flushDiscreteUpdates: Cannot flush updates when React is already rendering

I'm seeing if I can dig up any context on them

**Comment by zephraph** [comment]
A large chunk of the test failures are from `FeatureAKG`

**Comment by damassi** [comment]
hmm 🤔

**Comment by damassi** [comment]
Going to close this until I find the time to work through the failures

**Pull request closed without merging**
