### PR TITLE
Move cohesion to be a dev dep of reaction

### PR DESCRIPTION
**Pull request by zephraph**
Given that cohesion is a direct dependency of force, including it as a direct dependency of reaction can lead to cases where it's duplicated in Force's bundle. I'm moving it to a dev dependency in reaction so that it'll still be installed and available when developing locally, but won't be included in the production output (and therefore duplicated in force). 

I haven't included it in this PR, but if there are other services that depend on reaction which should also use cohesion then we should add cohesion as a peer dep too.

### CODE REVIEW

**Comment by eessex** [comment]
@zephraph are you saying we'll need to install cohesion on all reaction-consuming apps to support this change? That would mean Positron and Rosalind for sure, not sure if there are more consumers, but I don't expect them to ever need Cohesion. 

I wonder if we can use resolvers or some other way to let force play nicer with the dependency? I fear that if we add cohesion to a reaction-consuming app that doesn't use it, it will get removed.

**Comment by zephraph** [comment]
How it's set up now, no. We would _not_ need to install cohesion on other apps. 

The only reason we'd need to do that is if they needed cohesion.

**Comment by eessex** [comment]
Ok sounds good! #mergeongreen

**Comment by artsyit** [comment]
:rocket: PR was released in [`v26.22.3`](https://github.com/artsy/reaction/releases/tag/v26.22.3) :rocket:

**Pull request merged**
