### PR TITLE
Exclude vertical from related articles canvas if article layout is news

### PR DESCRIPTION
**Pull request by eessex**
Addresses https://artsyproduct.atlassian.net/browse/GROW-910

screen shot 2019-02-13 at 5 51 17 pm

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit b52c8ed3ec0b3cb30178a3c88d94ac6c61e9ed1a

https://deploy-preview-2018--artsy-reaction.netlify.com

**Comment by damassi** [comment]
Ahh accidentally merged this. Can revert if need be @xtina-starr.

**Comment by artsyit** [comment]
:rocket: PR was released in v13.0.10 :rocket:

**Comment by xtina-starr** [comment]
@damassi yeah, but it should be fine considering the change is relatively minor.

**Comment by damassi** [comment]
Ok cool, sorry about that

**Comment by xtina-starr** [comment]
No worries!

**Pull request merged**
