### PR TITLE
[CarouselV3] Update react-flickity-component@3.3.0

### PR DESCRIPTION
**Pull request by damassi**
This completes a cycle of work with @kierangillen around SSR rendering and the new flickity carousel. 

Removes the patch we had in place in favor of a new `static` prop, added in this [upstream PR](https://github.com/theolampert/react-flickity-component/pull/64).

Companion Force PR: https://github.com/artsy/force/pull/4040

(Assigning to @pepopowitz as @kierangillen is currently on 🍹)

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 9df4ba18623d542e082075659671e96a820b5fd1

https://deploy-preview-2408--artsy-reaction.netlify.com

**Comment by kierangillen** [comment]
@damassi why not delete the patch file entirely?

**Comment by damassi** [comment]
@kierangillen - yep it's deleted

**Comment by pepopowitz** [comment]
🎉

**Comment by artsyit** [comment]
:rocket: PR was released in v16.11.4 :rocket:

**Pull request merged**
