### PR TITLE
set up artist collections rail test

### PR DESCRIPTION
**Pull request by xtina-starr**
Address: [GROW-1139](https://artsyproduct.atlassian.net/browse/GROW-1139)

This uses `showCollectionsRail` to determine when to show the rails on the artist page.

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 4b3205cbc125a369e721534b38f5404e2ea47e62

https://deploy-preview-2172--artsy-reaction.netlify.com

**Comment by eessex** [comment]
Looks good from here, the props change makes more sense for sure 👍

**Comment by xtina-starr** [comment]
I'm not sure what's up with the jest test and why they haven't finished running.

**Comment by xtina-starr** [comment]
This is passing on circle ci https://circleci.com/gh/artsy/reaction/29430

Going to go ahead and merge.

**Comment by artsyit** [comment]
:rocket: PR was released in v15.5.5 :rocket:

**Pull request merged**
