### PR TITLE
Remove BidFlow from router

### PR DESCRIPTION
**Pull request by damassi**
Remove all router code from the bid flow. 

Merging to get this hotfix out.

### CODE REVIEW

**Comment by artsyit** [comment]
:rocket: PR was released in `v25.27.9` :rocket:

**Comment by dleve123** [comment]
@damassi Were there any further problems found with this code, or did you removal out of caution?

**Comment by damassi** [comment]
There are two parts to the auction flow -- the redirects that happen when registering from an auction page and entering a credit card, and then the artwork-only page flow (bid, enter credit card, raise bid, etc) -- we removed the first part, but not the second, which became apparent when clicking the bid button, as we then tried to do a "soft" jump via the router to the bid form page but that had been unmounted on the force side of things. This pr removes the remainder of code.

**Comment by damassi** [comment]
Its a bit of a bummer to remove all of this (versus being able to toggle off) but we have references in the future to re-add when the credit card issue is resolved.

**Pull request merged**
