### PR TITLE
Thread through description to search result items

### PR DESCRIPTION
**Pull request by dblandin**
Show the `descriptions` from `SearchableItem` results returned from Metaphysics. Metaphysics should handle the formatting of the description. Reaction may truncate the attribute as needed.

2019-03-20-183708_1222x369_scrot

2019-03-20-183725_1265x544_scrot
2019-03-20-183741_1668x539_scrot

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 0e4962eb41534b4a16ec070527003e625c54f5e8

https://deploy-preview-2193--artsy-reaction.netlify.com

**Comment by dblandin** [comment]
@mzikherman I just chatted with Jeffrey and we're going to strip the html tags in the description from Metaphysics. I'm also planning to split up Palette's `<ReadMore>` component so we can reuse the truncation but drop the "Read more" link and expand behavior.

**Comment by damassi** [comment]
@dblandin - See [Truncator](https://github.com/artsy/reaction/blob/master/src/Components/Truncator.tsx)

**Comment by dblandin** [comment]
> @dblandin - See Truncator

@damassi Thank you!! :100: Do you think we should pull that into Palette eventually?

**Comment by damassi** [comment]
Yup! could live beside https://palette.artsy.net/elements/layout/readmore/

**Comment by mzikherman** [comment]
@dblandin I'm not seeing where the HTML handling of the description for collections is being done.

Feel free to merge when you're comfortable. This looks fine to me, we can continue to iterate as needed 👍

**Comment by dblandin** [comment]
@mzikherman Commented about that in https://github.com/artsy/reaction/pull/2193#issuecomment-475058213. I'm planning to strip the html tags within Metaphysics using [stripTags](https://github.com/artsy/metaphysics/blob/master/src/lib/helpers.ts#L88-L91).

**Comment by dblandin** [comment]
@mzikherman Here's that Metaphysics PR: https://github.com/artsy/metaphysics/pull/1617

**Comment by dblandin** [comment]
Going to merge this in :+1:

**Comment by artsyit** [comment]
:rocket: PR was released in v15.7.0 :rocket:

**Pull request merged**
