### PR TITLE
Fully roll out artist recommendations

### PR DESCRIPTION
**Pull request by dblandin**
Paired on this with @kierangillen!

This PR rolls out the new Artist Recommendations component on the Artist page's Overview tab. This component replaces the existing Related Artists tab and `/related-artists` route.

We'll redirect any user navigating directly to `/artist/:artist_id/related-artists` to the overview tab. We've talked about either rendering the new component's content on this route or automatically scrolling the user down to the new component on the overview tab via an anchor tag. That enhancement might come in a subsequent release. cc/ @stephen-i-chan

:tophat: to @pepopowitz! :tada: 

2019-05-01-143442_1798x1204_scrot

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit bd5c6a75a85eb127e0e1f77bf41ffdcba53b7cdc

https://deploy-preview-2360--artsy-reaction.netlify.com

**Comment by mzikherman** [comment]
Looks good to me! I think the default redirect/route handling will treat `/related-artists` as an unhandled sub-route of the artist app, and will thus redirect to the `/` page.

**Comment by kierangillen** [comment]
@mzikherman Yup we tested the redirect and can confirm it worked :)

**Comment by artsyit** [comment]
:rocket: PR was released in v16.7.0 :rocket:

**Pull request merged**
