### PR TITLE
[WIP] Adds chromatic for visual regression review

### PR DESCRIPTION
**Pull request by orta**
Current build, where everything is accepted because it's the first run: https://www.chromaticqa.com/build?appId=5b3b6f2fe2fa56002499d20f&number=1

Not on CI yet, but did work with `yarn chromatic test --app-code="xxx" --script-name="start-storybook" --storybook-port=9001`

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 1abbf17867ab6f8744db9ceb04ef335579a18a80

https://deploy-preview-943--artsy-reaction.netlify.com

**Comment by orta** [comment]
Hrm, so we have roughly 50 tests which are a bit unpredictable on chromatic right now

**Comment by orta** [comment]
I've tried passing in a user and a token to the chromatic script, the token will only last ~3 weeks, but I can get a user created on prod then migrated to staging in that time if this works 👍

**Comment by orta** [comment]
Seeing a lot of:

```
{ Error: Could not parse CSS stylesheet
    at exports.createStylesheet (/home/circleci/artsy/reaction/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
    at HTMLStyleElementImpl._updateAStyleBlock (/home/circleci/artsy/reaction/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
    at HTMLStyleElementImpl._childTextContentChangeSteps (/home/circleci/artsy/reaction/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:36:12)
    at TextImpl.replaceData (/home/circleci/artsy/reaction/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:73:23)
    at TextImpl.appendData (/home/circleci/artsy/reaction/node_modules/jsdom/lib/jsdom/living/nodes/CharacterData-impl.js:43:10)
    at Text.appendData (/home/circleci/artsy/reaction/node_modules/jsdom/lib/jsdom/living/generated/CharacterData.js:76:21)
    at Object.insertRules (webpack-internal:///1:742:16)
    at StyleSheet.inject (webpack-internal:///1:1175:9)
    at ComponentStyle.generateAndInjectStyles (webpack-internal:///1:2071:20)
    at StyledComponent.generateAndInjectStyles (webpack-internal:///1:1759:40)
  detail: '\n/* sc-component-id: sc-bdVaJa */\n\n/* sc-component-id: sc-bwzfXH */\n\n/* sc-component-id: sc-htpNat */\n\n/* sc-component-id: sc-bxivhb */\n\n/* sc-component-id: sc-ifAKCX */\n\n/* sc-component-id: sc-EHOje */\n\n/* sc-component-id: sc-bZQynM */\n\n/* sc-component-id: sc-gzVnrw */\n\n/* sc-component-id: sc-global-3935376445 */\n@-ms-viewport{{width:device-width;}} html{-webkit-box-sizing:border-box;box-sizing:border-box;-ms-overflow-style:scrollbar;} *,*::before,*::after{-webkit-box-sizing:inherit;box-sizing:inherit;} ,html,body,div,span,applet,object,iframe,h1,h2,h3,h4,h5,h6,p,blockquote,pre,a,abbr,acronym,address,big,cite,code,del,dfn,em,img,ins,kbd,q,s,samp,small,strike,strong,sub,sup,tt,var,b,u,i,center,dl,dt,dd,ol,ul,li,fieldset,form,label,legend,table,caption,tbody,tfoot,thead,tr,th,td,article,aside,canvas,details,embed,figure,figcaption,footer,header,hgroup,main,menu,nav,output,ruby,section,summary,time,mark,audio,video{margin:0;padding:0;border:0;font-size:100%;font:inherit;vertical-align:baseline;} article,aside,details,figcaption,figure,footer,header,hgroup,main,menu,nav,section{display:block;} *[hidden]{display:none;} body{line-height:1;} ol,ul{list-style:none;} blockquote,q{quotes:none;} blockquote:before,blockquote:after,q:before,q:after{content:\'\';content:none;} table{border-collapse:collapse;border-spacing:0;} *:focus{outline:none;} html,body,#root{height:100%;} body{margin:0;padding:0;} html,body{font-family:\'AGaramondPro-Regular\';font-size:16px;line-height:24px;}\n/* sc-component-id: GlobalStyles-pscdiw-0 */\n.GlobalStyles-pscdiw-0 {} .kIkANC a{cursor:pointer;color:inherit;-webkit-transition:0.25s;transition:0.25s;} .kIkANC a:hover{color:#000;} .kIkANC a:active{color:#000;} .kIkANC a.noUnderline{-webkit-text-decoration:none;text-decoration:none;} .kIkANC a.noUnderline:hover{-webkit-text-decoration:underline;text-decoration:underline;} .kIkANC a.colorLink{-webkit-text-decoration:none;text-decoration:none;color:#6E1EFF;} .kIkANC a.colorLink:hover{-webkit-text-decoration:underline;text-decoration:underline;} .kIkANC .sc-bwzfXH a{color:inherit;} .kIkANC .sc-bwzfXH a:hover{color:#000;} .kIkANC .sc-bwzfXH a:active{color:#000;} .kIkANC .sc-bwzfXH a.noUnderline{-webkit-text-decoration:none;text-decoration:none;} .kIkANC .sc-bwzfXH a.noUnderline:hover{-webkit-text-decoration:underline;text-decoration:underline;} .kIkANC .sc-bwzfXH a.colorLink{-webkit-text-decoration:none;text-decoration:none;color:#6E1EFF;} .kIkANC .sc-bwzfXH a.colorLink:hover{-webkit-text-decoration:underline;text-decoration:underline;} .kIkANC .sc-htpNat a{color:inherit;} .kIkANC .sc-htpNat a:hover{color:#000;} .kIkANC .sc-htpNat a:active{color:#000;} .kIkANC .sc-htpNat a.noUnderline{-webkit-text-decoration:none;text-decoration:none;} .kIkANC .sc-htpNat a.noUnderline:hover{-webkit-text-decoration:underline;text-decoration:underline;} .kIkANC .sc-htpNat a.colorLink{-webkit-text-decoration:none;text-decoration:none;color:#6E1EFF;} .kIkANC .sc-htpNat a.colorLink:hover{-webkit-text-decoration:underline;text-decoration:underline;} .kIkANC .sc-bxivhb a{color:#000;-webkit-text-decoration:none;text-decoration:none;text-transform:uppercase;} .kIkANC .sc-bxivhb a:hover{-webkit-text-decoration:underline;text-decoration:underline;}\n/* sc-component-id: Grid-qyt2ah-0 */\n\n/* sc-component-id: Grid__Row-qyt2ah-1 */\n\n/* sc-component-id: Grid__Col-qyt2ah-2 */\n\n/* sc-component-id: Flex-s16agd44-0 */\n\n/* sc-component-id: Box__BorderBox-s8jehsh-0 */\n\n/* sc-component-id: Box-s8jehsh-1 */\n\n/* sc-component-id: BreakpointVisualizer__StyledBox-dasofy-0 */\n\n/* sc-component-id: Section__Header-liedcm-0 */\n\n/* sc-component-id: ReadMore__ReadMoreLinkContainer-s178fy9-0 */\n\n/* sc-component-id: ReadMore__Container-s178fy9-1 */\n\n/* sc-component-id: TextLink__StyledTextLink-pwn95u-0 */\n\n/* sc-component-id: sc-htoDjs */\n\n/* sc-component-id: MarketInsights__MarketInsightsContainer-s16h7vui-0 */\n\n/* sc-component-id: MarketInsights__MarketInsightsDataContainer-s16h7vui-1 */\n\n/* sc-component-id: MarketInsights__FeedbackContainer-s16h7vui-2 */\n\n/* sc-component-id: MarketInsights__TooltipContainer-s16h7vui-3 */\n\n/* sc-component-id: Separator-s1stngne-0 */\n\n/* sc-component-id: Icon-s13f8sed-0 */\n\n/* sc-component-id: FollowIcon__FollowIconContainer-s1y8bnim-0 */\n\n/* sc-component-id: FollowIcon__Follow-s1y8bnim-1 */\n\n/* sc-component-id: FollowIcon__Unfollow-s1y8bnim-2 */\n\n/* sc-component-id: FollowIcon__Following-s1y8bnim-3 */\n\n/* sc-component-id: FollowIcon__FollowingHover-s1y8bnim-4 */\n\n/* sc-component-id: FollowIcon__FollowHover-s1y8bnim-5 */\n\n/* sc-component-id: sc-keyframes-FiaaB */\n@-webkit-keyframes FiaaB{100%{-webkit-transform:rotate(360deg);-ms-transform:rotate(360deg);transform:rotate(360deg);}} @keyframes FiaaB{100%{-webkit-transform:rotate(360deg);-ms-transform:rotate(360deg);transform:rotate(360deg);}}\n/* sc-component-id: Spinner__StyledSpinner-s1a7qnq6-0 */\n\n/* sc-component-id: Button-k88h3f-0 */\n\n/* sc-component-id: Button__Container-k88h3f-1 */\n\n/* sc-component-id: ArtworkSidebar__ArtworkSidebarContainer-weyg4q-0 */\n\n/* sc-component-id: Avatar-s15v0bdm-0 */\n',
  type: 'css parsing' }
```
 in the logs.

Wonder if updating jsdom or styled-components can fix that

**Comment by orta** [comment]
```sh
~/dev/projects/artsy/js/libs/reaction-force chromatic*
❯ node
> @-ms-viewport{{width:device-width;}}
> const JSDOM = require('jsdom').JSDOM

undefined
>
> new JSDOM("<style>@-ms-viewport{{width:device-width;}}</style>")
Error: Could not parse CSS stylesheet
    at exports.createStylesheet (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:35:21)
    at HTMLStyleElementImpl._updateAStyleBlock (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:67:5)
    at HTMLStyleElementImpl._poppedOffStackOfOpenElements (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:42:10)
    at module.exports.OpenElementStack.pop (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/lib/jsdom/browser/htmltodom.js:17:12)
    at Object.endTagInText [as END_TAG_TOKEN] (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:2057:20)
    at module.exports.Parser._processToken (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:607:38)
    at module.exports.Parser._processInputToken (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:639:14)
    at module.exports.Parser._runParsingLoop (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:409:14)
    at module.exports.Parser.parse (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/node_modules/parse5/lib/parser/index.js:322:10)
    at Object.parse (/Users/orta/dev/projects/artsy/js/libs/reaction-force/node_modules/jsdom/node_modules/parse5/lib/index.js:11:19) @-ms-viewport{{width:device-width;}}
```

Looks like it's this `@-ms-viewport` CSS attribute, seen it in a bunch of places

**Comment by orta** [comment]
That code comes from https://github.com/dragma/styled-bootstrap-grid - but I'm not sure what could potentially be wrapping it with extra braces?

**Comment by zephraph** [comment]
This PR is pretty outdated at this point. I'm going to close it, but we can revisit later.

**Pull request closed without merging**
