### PR TITLE
[Refactor] Replace mobile LoginForm `metaphysics` calls with `fetchQuery`

### PR DESCRIPTION
**Pull request by damassi**
Addresses https://github.com/artsy/reaction/pull/2887
Related https://github.com/artsy/reaction/pull/2885

Updates `LoginForm` and `helpers` to use `fetchQuery` instead of `metaphysics`, and deletes `metaphysics` fetch utility. 

login

### CODE REVIEW

**Comment by alloy** [comment]
Ace :sparkles:

**Comment by artsyit** [comment]
:rocket: PR was released in v21.2.2 :rocket:

**Comment by damassi** [comment]
@alloy - I presume the `cacheConfig: { force: true }` is needed here as well?

**Comment by alloy** [comment]
Unsure. In this case the input variables change, which is a thing that you would normally take into account when caching responses.

**Comment by damassi** [comment]
Ahh right right

**Pull request merged**
