### PR TITLE
Clean `.cache` as part of `clean` task

### PR DESCRIPTION
**Pull request by pepopowitz**
As [discussed in Slack](https://artsy.slack.com/archives/C02BC3HEJ/p1552399118228900) - 

I am having trouble getting things running locally, and it was suspected that I need to clean my yarn cache. @damassi suggested I add it to the clean task, as well.

### CODE REVIEW

**Comment by zephraph** [comment]
Could you link the slack conversation or provide a bit more context? I'm :+1: generally, I'm just curious what issue spurred this on.

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit a6be15fa617c8e6ebafbccfb511e3d5de49b1a2b

https://deploy-preview-2146--artsy-reaction.netlify.com

**Comment by pepopowitz** [comment]
@zephraph https://artsy.slack.com/archives/C02BC3HEJ/p1552399118228900

I am having trouble getting things running locally, and it was suspected that I need to clean my yarn cache. @damassi suggested I add it to the `clean` task, as well.

**Comment by artsyit** [comment]
:rocket: PR was released in v15.1.1 :rocket:

**Pull request merged**
