### PR TITLE
🔥blazing fast builds 🔥

### PR DESCRIPTION
**Pull request by zephraph**
_Let's get these builds running faster, faster_.

Let's see how much time we can trim... ⏳

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 03722ac5d618e79a20c8d2c5aae0b23292ea7182

https://deploy-preview-1523--artsy-reaction.netlify.com

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 9571fee8ede1c20200cfc93def66e9cc5c72fd93

https://deploy-preview-1523--artsy-reaction.netlify.com

**Comment by zephraph** [comment]
image
image
image
image
image

😱

**Comment by zephraph** [comment]
So I've got builds to the sub-50 second range. 

I did two things: 

1. Update the yarn caching policy to have a faster general case. Essentially there's no more cache fallback and I removed `yarn --check-files`. That means when a dependency changes it'll take longer than it did previously, but the general case is faster
2. Updated the test executors by 2. This will increase the memory consumption but hopefully not to a level that'll start starving other jobs. We'll have to kind of keep an eye on it. Tests are our slowest thing though and that trend will only continue as we write more of them.

**Comment by orta** [comment]
Impressive that it's just moving some strings around 👍

**Comment by zephraph** [comment]
Isn't that most coding at the end of the day? 😄

**Pull request merged**
