### PR TITLE
Rename Feature Article Fixture

### PR DESCRIPTION
**Pull request by ashleyjelks**
Renames test fixture for non-sponsored feature articles.

### CODE REVIEW

**Comment by ashleyjelks** [comment]
merge on green

**Comment by artsyit** [comment]
:rocket: PR was released in v16.18.2 :rocket:

**Comment by eessex** [comment]
Heads up this may affect tests in positron and force, where we use these fixtures as well.

**Comment by ashleyjelks** [comment]
This particular change should be ok bc its only used for the new Display Ads, but good to know!

**Pull request merged**
