### PR TITLE
Removes react-flickity-component

### PR DESCRIPTION
**Pull request by kierangillen**
- Removes `react-flickity-component`
- Adds `flickity` as a peer and dev dependency only
- Deletes CarouselV2
- We can fully consolidate CarouselV3 into Carousel once further QA is completed

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 638b769c57d5cca28b90fd65580099ee7fa232af

https://deploy-preview-2497--artsy-reaction.netlify.com

**Comment by damassi** [comment]
👍 

merge on green

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 61fa8921cf94e3a0074aa71dd8282c4c377dfa3e

https://deploy-preview-2497--artsy-reaction.netlify.com

**Comment by artsyit** [comment]
:rocket: PR was released in v16.13.5 :rocket:

**Pull request merged**
