### PR TITLE
Search results loading skeleton

### PR DESCRIPTION
**Pull request by dblandin**
2019-04-18-130922_2246x1079_scrot

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 5b2ff8e2dfdb75f4c70cf130b3c2f2ffec0f1425

https://deploy-preview-2305--artsy-reaction.netlify.com

**Comment by mzikherman** [comment]
LGTM! I would possibly move this to be under `Apps/Search/Components` since it's a pretty app-specific component.

**Comment by zephraph** [comment]
This looks so good!

**Comment by dblandin** [comment]
Going to pull in this first iteration :+1:

**Comment by artsyit** [comment]
:rocket: PR was released in v16.1.0 :rocket:

**Pull request merged**
