### PR TITLE
Deprecate old ads for series landing pages

### PR DESCRIPTION
**Pull request by pepopowitz**
Addresses https://artsyproduct.atlassian.net/browse/GROW-1348 and https://artsyproduct.atlassian.net/browse/GROW-1349.

* Replaces NewDisplayCanvas with DisplayAd in SeriesLayout.tsx
* Updates tests to account for the replacement
* Consolidates the SeriesLayoutAdsEnabled and SeriesLayout tests

### CODE REVIEW

**Comment by l2succes** [comment]
Looks good! merge on green

**Comment by ashleyjelks** [comment]
We need to explicity pass the prop `isSeries` here so that the display ad background is black.

**Comment by ashleyjelks** [comment]
> We need to explicity pass the prop `isSeries` here so that the display ad background is black and that the border top prop is different.
> 
> Series landing pages are slightly different in style than the others, see here:
> 
> https://github.com/artsy/reaction/blob/d2ab4183dffa9915720a30bffe56b835c0f7f765/src/Components/Publishing/Display/DisplayAd.tsx#L86
> 
> https://github.com/artsy/reaction/blob/d2ab4183dffa9915720a30bffe56b835c0f7f765/src/Components/Publishing/Display/DisplayAd.tsx#L87

Actually

**Comment by artsyit** [comment]
:rocket: PR was released in v16.18.14 :rocket:

**Pull request merged**
