### PR TITLE
Lazy-load recently viewed

### PR DESCRIPTION
**Pull request by zephraph**
The recently viewed component currently shows up at the _bottom_ of the artist paged for an authenticated user. Being that it's behind a login, it has _no_ value for SEO. Currently, every image in the component is configured as the large and there's no lazy loading happening. 

This PR is a quick and dirty fix that adds a new js dependency to the bundle but has significant impact on the above-the-fold performance of the artist page for an authenticated user. 

This isn't the only work that needs to happen. The images need to be properly sized and preferably individually lazy loaded. For now, this'll do. 

If one of us gets time, we can write our own lazy loading component and remove the js dependency. Until now, it gives us a capability that we need and I think is worth the cost.

This is a drive by optimization on my part, and I haven't done a deep dive in verifying this. In particular, it'd be really beneficial if someone could help verify that it works okay w/ SSR. If not, I can take a stab at a super simple lazy-loader w/ SSR compatibility. 

With recently viewed

image 2

Without recently viewed

Not authenticated

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 7909c697137cd250ea886d379ce6789143e35b5b

https://deploy-preview-1111--artsy-reaction.netlify.com

**Comment by alloy** [comment]
These look like great savings!

FYI next sprint I _may_ replace this change (and the dep) by a Relay based ‘defer’ solution.

**Comment by orta** [comment]
Defer is covered in http://artsy.github.io/blog/2018/07/25/Relay-Networking-Deep-Dive/ BTW

**Comment by zephraph** [comment]
I think we could likely use both approaches in concert. So, from what I can gather, Relay's defer statement makes it where when the fragment mounts then the data fetch will happen. If that's the case, then using the lazy-load component would show the section when it's coming into view and relay would kick off the fetch.

**Comment by damassi** [comment]
This is cool -- I like that the library covers both images as well components. 

While this is a different use-case, one thing I want to keep on our radar (for the future) is https://github.com/smooth-code/loadable-components, which bundle splits code that can be loaded client-side as well as server-side. The infra for this is already in place in Reaction and Force, though I think we would need to verify that consumed lib code can be properly bundle split from Force's Webpack config -- meaning, that the dynamic `import()` statements aren't transpired before being published to NPM. 

Otherwise, LGTM 👍

**Comment by joeyAghion** [comment]
Regarding "the images need to be properly sized," this is already happening, right? The source image is the `large` version, but they are run through the dynamic resizer and CDN, from what I can tell.

Seems like a great step in any case.

**Comment by mzikherman** [comment]
> Regarding "the images need to be properly sized," this is already happening, right? The source image is the large version, but they are run through the dynamic resizer and CDN, from what I can tell.

Unfortunately not @joeyAghion , we only instituted that (recently) for the artwork grid. This is 'fill width' (a rail of recently viewed works), which doesn't have that same resizing (where the source is `large`). This just renders `large`.

We should change that! I was surprised to see that, since it's only for logged in users it makes sense webpagetest didn't call it out.

**Comment by joeyAghion** [comment]
Ah, my mistake. Was inspecting the recently-viewed component on an artwork page and didn't realize it was different on the artist page.

**Pull request merged**
