### PR TITLE
[WIP] Onboarding snapshot tests

### PR DESCRIPTION
**Pull request by kanaabe**
TODO
- [ ] Mock metaphysics for more accurate snapshots

This is a big diff but it's mostly just generated code from the snapshots. I didn't add a snapshot test for Wizard because it doesn't contain any styles. Wizard will benefit from having lots of unit tests though.

### CODE REVIEW

**Comment by alloy** [comment]
> Mock metaphysics for more accurate snapshots

@kanaabe Ah yes, I’ve been thinking long about this, it would be beneficial to actually use Relay to ensure that all queries are correct. I settled on the following:

* Unit tests benefit from data being stubbed local to the test, so a local stubbed copy of the MP schema that Relay queries against is probably the way to go. I was planning on wrapping https://github.com/relay-tools/relay-local-schema, but I just found that somebody else already did that: https://github.com/1stdibs/relay-mock-network-layer
* For storybooks we need more complete data and stubbing that becomes tedious as you’re adding/removing fields, so for this purpose I started writing some tooling that would use a ‘VCR’ library to record _actual_ network requests made by Relay to MP for later replay.

What do you think?

**Comment by kanaabe** [comment]
@alloy interesting, coming from significantly less Relay experience, I was thinking of using https://github.com/jefflau/jest-fetch-mock to mock the metaphysics level fetch. But this seems like we would have slightly more control. Would snapshot tests use the network mock too?

**Comment by alloy** [comment]
During a retro about snapshots/unit tests/storybooks we came to the conclusion that we’d want:

1. Storybooks for components that show their full behaviour
2. Use [storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots) to create snapshots of those ^ stories
3. Plain unit tests for logic inside components, no snapshots whatsoever

Recording requests in a browser (storybooks) is hard-ish, which is what 2 could also nicely solve. Namely, when running the storyshots we allow it to record the requests, and on a static deploy of storybooks it can use those recorded requests.

**Comment by orta** [comment]
Or even better, something like: https://github.com/oblador/loki so we get visual regressions rather than text

**Comment by kanaabe** [comment]
@alloy Ah, so this PR contradicts what was agreed on before. Sorry I didn't know about that and was looking at https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=4&projectKey=AR&modal=detail&selectedIssue=AR-43.

I'll close this for now then and try out storyshots.

**Comment by alloy** [comment]
@kanaabe Sorry about that. I don’t think that retro outcome ever got codified :( Thanks for taking that on!

**Comment by alloy** [comment]
@orta I definitely think we should be looking at such tooling in the future, but it doesn’t fix the specific issue that I mentioned is fixed by having storyshots and being able to record requests there.

**Comment by orta** [comment]
Agree ^

**Pull request closed without merging**
