### PR TITLE
@zephraph => Link to /cv if there is > 3 exhibitions

### PR DESCRIPTION
**Pull request by mzikherman**
but only display a max of 3

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 6ab5b598fec4262fac8338d5fc488b19727d4d14

https://deploy-preview-985--artsy-reaction.netlify.com

**Comment by zephraph** [comment]
I can't really tell from this, but there's some nuance to how selected exhibitions work that we didn't get right the first time around. It's not that it's just supposed to be 3 exhibitions, but also that it's supposed to be the _3 most important_ exhibitions. I'm not sure how we define importance, but I got the sense that it was something other than what chronologically came latest. I haven't compared this w/ what's in production yet though, so I'm not sure if it captures those requirements.

**Comment by mzikherman** [comment]
Good point. We get the results back in relevance order, but not in chronological order, so we perform some grouping/sorting here. The important thing is just to make sure we don't sort, and _then_ truncate to 3 results. That might mean we don't get the actual 3 most important ones.

So I think this is actually sufficient. A previous iteration of this wound up doing a lot more sorting on the client, now we perform a relevance sort on the server.

**Comment by zephraph** [comment]
Sounds good to me

**Pull request merged**
