### PR TITLE
Creates patch for react-flickity-component to fix flicker

### PR DESCRIPTION
**Pull request by kierangillen**
- Patches Flickity to remove `renderPortal()` to prevent flicker on page load. 
- Will remove this patch once https://github.com/theolampert/react-flickity-component/pull/64 is merged.

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 3878f327a1aa8bedbb66bfc0fcd5005049d05d7e

https://deploy-preview-2388--artsy-reaction.netlify.com

**Comment by damassi** [comment]
👍

**Comment by damassi** [comment]
Once this is deployed and force is updated with the new version be sure to pull master, run `yarn unlink @artsy/reaction` then `yarn --check-files`, and test that things are working.

**Comment by artsyit** [comment]
:rocket: PR was released in v16.8.15 :rocket:

**Pull request merged**
