### PR TITLE
Add docs for relay data mocking

### PR DESCRIPTION
**Pull request by ds300**
see https://github.com/artsy/reaction/pull/1854#issuecomment-454100304 for context

### CODE REVIEW

**Comment by orta** [comment]
Yeah, this is a good call

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit b32e439f980b2fc2da5875efb8b0068a588c8106

https://deploy-preview-1898--artsy-reaction.netlify.com

**Comment by damassi** [comment]
Sweet 👍

**Comment by alloy** [comment]
✨

**Pull request merged**
