### PR TITLE
[PATCH makeOffer] Add a helpful message to “offer” step

### PR DESCRIPTION
**Pull request by pepopowitz**
JIRA: https://artsyproduct.atlassian.net/browse/PURCHASE-576

This PR adds a helpful message to the "offer" step, helping them understand what it means to "make an offer". See screenshot below.

No tests are included in this change. The message displays unconditionally, and an "it renders" test doesn't seem too valuable.

image

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 3e92da347a7c5043b2f1cfab4f6b5d4551e067c8

https://deploy-preview-1493--artsy-reaction.netlify.com

**Comment by pepopowitz** [comment]
No, I wasn't aware of the responsive props. Thanks for the tip! I didn't think to look in Zeplin for a responsive view, but now I see it. 

I don't see very many responsive props in the changed file, so I wonder if there are other similar things that were also missed. After I fix the ones you pointed out, I'll do a quick comparison between Zeplin/localhost to see if I can find other differences.

**Comment by pepopowitz** [comment]
@ds300 changes have been made. Let me know what you think!

**Comment by ds300** [comment]
merge on green

**Pull request merged**
