### PR TITLE
Update React Types

### PR DESCRIPTION
**Pull request by zephraph**
Reaction is on React 16.4. This is just a bump to types. I'm going to open a similar PR on force, but that'll be actually updating react too.

### CODE REVIEW

**Comment by alloy** [comment]
Aww yeah, dates in tests 🤘

**Comment by zephraph** [comment]
@alloy can you kick off the test again? It should pass now.

I need to get perms for circleci.

**Comment by alloy** [comment]
Hmm, looks like I don’t have the permission either, which is weird. @damassi @l2success do you know more about this setup?

**Comment by damassi** [comment]
@zephraph and @alloy - not sure exactly; normally you just have to log in and it will understand team permissions.

**Comment by alloy** [comment]
Weird, I do have the permissions on desktop, just not on mobile :| Well, it’s green now, so 👍

**Pull request merged**
