### PR TITLE
@dblandin => Adds all other entity tabs

### PR DESCRIPTION
**Pull request by mzikherman**
search

This adds the other tabs for entities. It also depends on https://github.com/artsy/metaphysics/pull/1593 for a few updates. It follows the same pattern as the other tabs, basically just paperwork!

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 5dbd8c422386a526a4ade7bef72bc0b59a75ebff

https://deploy-preview-2168--artsy-reaction.netlify.com

**Comment by alloy** [comment]
Aren’t all of these tabs identical, besides for the `entities` argument? Can’t that be a single component/container and pass in `entities` as a fragment argument to spreads for each type?

**Comment by mzikherman** [comment]
Yes, but this is just the first iterative step. The next step is going to be dropping more specific rendering for each tab, which would require the tab contents component to have their own fragments. So each tab might need a `... on Show { .... }` to render the shows tab, etc.

I deliberately thus wanted to include a fully functional refetch container (for pagination) with fragments and little placeholder renders already defined for each tab.

**Comment by mzikherman** [comment]
@alloy I edited my comment above, lmk if it makes sense ^. 

The *tl;dr* is that the next steps will have these tabs start to diverge, so I wanted to have these start out fully distinct and encapsulated in their own components, and _not_ shared. We can consolidate later once we get closer to the finished design and see where we're at.

**Comment by alloy** [comment]
Yup, makes absolute sense, thanks for the update! 👍 

(Perhaps next time, to save a reviewer and you some time, add a little line that says it's not DRY yet because of next iterative steps?)

**Comment by artsyit** [comment]
:rocket: PR was released in v15.5.0 :rocket:

**Pull request merged**
