### PR TITLE
Adds a user agent to the metaphysics fetch

### PR DESCRIPTION
**Pull request by orta**
This at least handles the reaction side of https://github.com/artsy/force/issues/2191

Happy to change what the text actually is, but at least it's there.

### CODE REVIEW

**Comment by alloy** [comment]
Doesn’t matter much right now, but at some point Reaction will probably be used in other apps, so maybe the user-agent should also hint at what the host app is? I'm fine with merging now as-is, though.

**Comment by kanaabe** [comment]
It already is in Positron 😄

**Comment by joeyAghion** [comment]
Yeah same thought... it would be nice if this was a default/fall-back and including systems could override it with their own agent identifiers. But this is much better than nothing!

**Comment by alloy** [comment]
@kanaabe My bad, thanks for rectifying! 🙏

**Comment by alloy** [comment]
One very explicit option, albeit somewhat repetitive, is to add a prop to the Artsy component for when no `environment` prop is specified https://github.com/artsy/reaction/blob/11bbc2bbea08a99a072e3a4cfa63e47c9ed18dc7/src/Components/Artsy.tsx#L76

```tsx
<ContextProvider userAgent="Force" {...}>
  <SweetTree />
</ContextProvider>
```

**Comment by joeyAghion** [comment]
Gonna merge this since it seems like an improvement on its own. Feel free to follow up with the configurability or not.

**Comment by orta** [comment]
Agree, going to take a quick look at configurability now 👍

**Pull request merged**
