### PR TITLE
Minor fit and finish work on shows tab

### PR DESCRIPTION
**Pull request by zephraph**
Just some minor visual updates to get things more in line w/ designs

### CODE REVIEW

**Comment by zephraph** [comment]
merge on green

**Comment by zephraph** [comment]
@mzikherman Not sure what the best way to achieve it is, but we need to hide these sections if they have no data. 

https://github.com/artsy/reaction/blob/b371eca28301aa7fd4916644e6078d9793db1b86/src/Apps/Artist/Routes/Shows/index.tsx#L25-L33

I'm guessing we'll had to add on to the fragment at this level to see if there are results? Not sure.

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 93349385f287b8f43d8228155669e3f5948884ed

https://deploy-preview-953--artsy-reaction.netlify.com

**Comment by mzikherman** [comment]
Yea, I guess for a component handling layout and needing to know existence/counts of the sub fragments, we need to copy the fragment and include it here just so we can access that.

(we don't need the whole fragment, just `edges { node { id } }` or something).

Alternatively, if its possible to accomplish the layout without leaving some of that styling up here (and being able to move spacers, etc. down to `Shows`), that would obviate the need for an 'existence-y' check at this level.

**Pull request merged**
