### PR TITLE
Remove dots from the artist images

### PR DESCRIPTION
**Pull request by ashkan18**
# Problem

https://artsyproduct.atlassian.net/browse/PURCHASE-1678

# Selfie
image

Removed dots by passing `pageDots` options from artists page and changed the height to 180 to reflect the new size.

cc: @samchieng

### CODE REVIEW

**Comment by sweir27** [comment]
@ashkan18 can you also post a screenshot of desktop and ensure that the spacing around the carousel matches the spec? 😄

**Comment by ashkan18** [comment]
good call! 
image

**Comment by samchieng** [comment]
@ashkan18 is it possible to override the `20px` left and right page margins for just the carousel on mobile? 

Also can decrease the padding between images from `10px` to `3px` for both desktop and mobile?

**Comment by sweir27** [comment]
Looks good to me once those ☝️ are addressed!

**Comment by ashkan18** [comment]
thanks to @sepans and @kierangillen 

# Desktop
image

# Mobile
image

**Comment by sweir27** [comment]
Woooo nice!

**Comment by artsyit** [comment]
:rocket: PR was released in v22.9.4 :rocket:

**Pull request merged**
