### PR TITLE
Show artwork sale message on editorial articles

### PR DESCRIPTION
**Pull request by williardx**
## Problem

We currently show artworks on Editorial that are for sale on Artsy. However, users do not see any pricing information which makes their for-sale status unclear.

## Solution

Show an artwork's `saleMessage` in an artwork's image caption on Editorial pages when we show an artwork. 

**Note**: The logic for `bidInfo` and `saleMessageDisplay` was lifted from Force: https://github.com/artsy/force/blob/b607b3b2bd9459981203c879ae3b3a3b04e9e587/src/v2/Components/Artwork/Details.tsx#L156. That code is thoroughly tested in Force and so tests are lighter here in comparison.

Screen Shot 2020-09-11 at 10 22 23 AM

Screen Shot 2020-09-11 at 10 22 38 AM

### CODE REVIEW

**Comment by dzucconi** [comment]
Thanks for the thorough solution here. If I'm reading correctly this will fire off individual queries for every caption within an article. Can we just lift the fragment into the parent query for these pages?

**Comment by dzucconi** [comment]
(I can imagine some pathological examples here; interestingly [query batching](https://github.com/artsy/metaphysics/pull/2661) would make this less of an issue)

**Comment by williardx** [comment]
@dzucconi The parent query for this is a query to Positron which doesn't store sale message data. We need the artwork slugs (which come from Positron) and once we have them can then query Gravity via Metaphysics for additional information.

**Comment by dzucconi** [comment]
@williardx OK, interesting... I'm gonna get the query batching PR merged anyway which would identify and merge these distinct queries into a single network request. But I'd be marginally concerned about this before that is turned on as I don't know if there are any articles floating around with a large number of artworks which could potentially cause some issues.

cc @mzikherman take a peek at this?

I suppose we can add this to the stack of evidence that these pages need some attention. 🤔

**Comment by williardx** [comment]
Yeah that makes sense -- I'm down to wait until https://github.com/artsy/metaphysics/pull/2661 is merged in.

**Comment by sweir27** [comment]
@williardx we're already pulling in _some_ artwork data to generate the rest of this view-- where is that being queried for?

**Comment by williardx** [comment]
As far as I can tell that data comes from Positron: We make a query using `ArticleQuery` https://github.com/artsy/force/blob/9fd6c485a217e90d40cbb0d58110e5e71bb9862f/src/desktop/apps/article/routes.tsx#L61 which can include this artwork fragment for `ImageCollection` and `ImageSet`: https://github.com/artsy/force/blob/9fd6c485a217e90d40cbb0d58110e5e71bb9862f/src/desktop/apps/article/queries/sectionFragments.js#L19.

**Comment by artsyit** [comment]
:rocket: PR was released in [`v28.6.0`](https://github.com/artsy/reaction/releases/tag/v28.6.0) :rocket:

**Pull request merged**
