### PR TITLE
[PUR-1727] Add medium field to artwork details

### PR DESCRIPTION
**Pull request by jpotts244**
Allow `medium` field to be displayed on Web/mobile web as part of the artwork details section
  - Displays `medium` as the first field in the metadata

Currently, this field is present on iOS
paired with @zephraph 🎉 

[Jira Ticket](https://artsyproduct.atlassian.net/browse/PURCHASE-1727)

### CODE REVIEW

**Comment by zephraph** [comment]
@jpotts244 to make sure your release goes in the proper place in the changelog (which isn't a _huge_ issue, but is nice when it works) is to update the label. 

We've got 4 versions:

`Version: Major` -- breaking change
`Version: Minor` -- feature update (like this change)
`Version: Patch` -- bug fix (the default)
`Version: Trivial` -- Not a code change, don't do a release

Just update it by changing the label on the PR

image

**Comment by zephraph** [comment]
Easy peasy! Good job :tada:

**Comment by artsyit** [comment]
:rocket: PR was released in v25.1.0 :rocket:

**Comment by jpotts244** [comment]
@zephraph ooOoOo thanks for the note! 
Ah I see, its a version bump whenever we are making changes to `reaction` itself, right? and not related to the graphql changes we made here?

**Comment by zephraph** [comment]
It's a version bump to reaction, yes. The GraphQL changes are a part of reaction  too. We were just updating data reaction asks for from metaphysics.

**Pull request merged**
