### PR TITLE
[FIX Order Forms] Fix bug that loses focus after 1 character

### PR DESCRIPTION
**Pull request by alloy**
@zephraph Can’t wait till we can use labels to designate the release type, I keep messing it up!

### CODE REVIEW

**Comment by alloy** [comment]
This is just s silly commit to trigger a release.

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit d4b40a4e4e1b545a9de82bfa7aa4a016c15f740a

https://deploy-preview-1512--artsy-reaction.netlify.com

**Comment by alloy** [comment]
And still I failed… I don’t know what’s up 😞 

/cc @damassi

**Comment by alloy** [comment]
I guess you can’t have spaces in the topic part of the commit message. https://github.com/artsy/reaction/pull/1514#issuecomment-437057093

**Pull request merged**
