### PR TITLE
add tabIndex={0} to preview links to get Safari to specify e.relatedTarget on blur

### PR DESCRIPTION
**Pull request by pepopowitz**
Inspired by this stackoverflow answer: https://stackoverflow.com/a/42764495

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 51919b908d3308af7b60f6f0ee1369e1ef724884

https://deploy-preview-2121--artsy-reaction.netlify.com

**Comment by mzikherman** [comment]
I guess I'm surprised this was an issue since aren't `<Link>` elements all `<a>` tags with an `href`, and so are thus 'selectable' and should provide that target? Thanks for digging!

**Comment by artsyit** [comment]
Yeah, I am also surprised. It doesn't seem like this should have done anything, but it definitely seems to have convinced Safari that these links were really links.

**Comment by pepopowitz** [comment]
Yeah, I am also surprised. It doesn't seem like this should have done anything, but it definitely seems to have convinced Safari that these links were really links.

**Comment by artsyit** [comment]
:rocket: PR was released in v14.3.3 :rocket:

**Pull request merged**
