### PR TITLE
Move to Storybooks 3.2

### PR DESCRIPTION
**Pull request by orta**
screen shot 2017-07-31 at 17 10 19

* Converts stories to use `*.story.tsx` like in Emission, and the Storybook examples
* Stories are now auto-loaded instead of being in a list
* **TODO:** Stories use a hierarchy

### CODE REVIEW

**Comment by orta** [comment]
Both "Fair" and "Save Button" do not work on master, and do not work on this version either FWIW

**Comment by l2succes** [comment]
Looks good 👏

**Comment by l2succes** [comment]
Looks good 👏

**Comment by orta** [comment]
^ Was me editing the PR, after the branch had been deleted.

**Pull request merged**
