### PR TITLE
@kanaabe => Tiny tweaks for writer

### PR DESCRIPTION
**Pull request by eessex**
Small tweaks to use components in Writer -- caption p styles, video accepts children

### CODE REVIEW

**Comment by kanaabe** [comment]
👍  Not sure what that peril error is about but code-wise this is great. I'm so happy this child pattern is working for us in Writer/Force!

**Comment by eessex** [comment]
@orta - does this error look familiar at all to you?

**Comment by eessex** [comment]
awesome thank you @orta

**Comment by orta** [comment]
This can be rebased with master 👍

**Comment by orta** [comment]
or maybe it'll just work on the next update, hard to say

**Comment by orta** [comment]
This should need a pretty serious rebase after #225 was merged too - sorry

**Pull request merged**
