### PR TITLE
[RelatedCollectionsRail]  fix related collections carousel

### PR DESCRIPTION
**Pull request by jiahaodavid**
addresses: [GROW-1332](https://artsyproduct.atlassian.net/browse/GROW-1332)

In this PR, we addresses the following:
- remove dots in the bottom
- group by 4
- do not strip anything from collections title

Screen Shot 2019-06-21 at 3 11 03 PM

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 13423d9dfcf6a2362a8b9d1f6955c7bf07c2c281

https://deploy-preview-2574--artsy-reaction.netlify.com

**Comment by l2succes** [comment]
Looks good! Congrats on your first PR @jiahaodavid 🎉

**Comment by artsyit** [comment]
:rocket: PR was released in v16.17.25 :rocket:

**Comment by jiahaodavid** [comment]
> Looks good! Congrats on your first PR @jiahaodavid 🎉

Thx again @xtina-starr

**Pull request merged**
