### PR TITLE
[Refactor] Rename `StorybooksRouter` to `ClientRouter` and consolidate Artsy/* imports

### PR DESCRIPTION
**Pull request by damassi**
**Updates:** 
- Rename `StorybooksRouter` to `ClientRouter`
- Consolidates all deeply nested import paths (`Artsy/Foo/Bar/Baz`) under `Artsy` root
- Create a new `Artsy/Utils` folder and move common tools under there (`ClientRouter`, `MockBoot`, etc) while also adding to `Artsy` root

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 1f01b33356973c1d3c87fc6fbd8bf4f624101433

https://deploy-preview-1276--artsy-reaction.netlify.com

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 46728e0a20bb94981de451ecfd9ed0dce4a53540

https://deploy-preview-1276--artsy-reaction.netlify.com

**Comment by alloy** [comment]
Btw, I also don’t think we should ever mix runtime and dev modules in the same export. E.g. mocking tools should go in an export like `reaction/testing`

**Comment by damassi** [comment]
@alloy 

> Btw, I also don’t think we should ever mix runtime and dev modules in the same export. E.g. mocking tools should go in an export like reaction/testing

This relates to our conversation yesterday -- although the file has mock in the name `mock` it doesn't mean it only relates to tests. This is for passing in data into our new app components -- for example from force, from a backbone model, or in other old code.

**Comment by damassi** [comment]
I'll go ahead and close this

**Pull request closed without merging**
