### PR TITLE
Add two more directions to chevron

### PR DESCRIPTION
**Pull request by jonallured**
Just dropping by to add the remaining directions to this chevron so that I can use it in Volt. Per @sepans's advice, I'm also switching to rotate so it's a little easier to read. 🌸

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 1573be8e2f68cf480e2fa55a3fd91a51992ffdb2

https://deploy-preview-1075--artsy-reaction.netlify.com

**Comment by damassi** [comment]
@jonallured - we've added this as an element in the most recent styleguide work: https://github.com/artsy/reaction/blob/master/src/Styleguide/Elements/Arrow.tsx

https://artsy-reaction.netlify.com/?selectedKind=Styleguide%2FElements&selectedStory=Arrow&full=0&addons=1&stories=1&panelRight=0&addonPanel=PeterPanen%2Fstorybook-addon-scissors%2Fpanelhttps://artsy-reaction.netlify.com/?selectedKind=Styleguide%2FElements&selectedStory=Arrow&full=0&addons=1&stories=1&panelRight=0&addonPanel=PeterPanen%2Fstorybook-addon-scissors%2Fpanelhttps://artsy-reaction.netlify.com/?selectedKind=Styleguide%2FElements&selectedStory=Arrow&full=0&addons=1&stories=1&panelRight=0&addonPanel=PeterPanen%2Fstorybook-addon-scissors%2Fpanel

**Comment by jonallured** [comment]
But that’ll use a font, no? I tried that first but got an empty square so that’s why I went this direction.

**Comment by damassi** [comment]
It uses our `<Icon />` component under the hood. If you saw a square than it means there's something up with how fonts are being loaded.

**Comment by zephraph** [comment]
As we're moving towards SVGs for icons, I'm 👍 for this (even given that we have an icon font for it already). There's going to be an initiative eventually to consolidate icons in Palette and those will all be SVG for web.

**Pull request merged**
