### PR TITLE
Delete unused files

### PR DESCRIPTION
**Pull request by eessex**
Delete unused files post force-merge. This first pass removes everything that was obviously unused by publishing code. I've left the router and relay elements for the moment because of tool-tips in articles, which I hope can be abstracted out of reaction to live in Force. 

There was only one real code-change, removing logic to display a `CollectionsRail` component in articles -- this was unused after an A/B test, and will be removed in the corresponding Force PR as well. 

<details>
  <summary>📦 Published PR as canary version: <code>26.54.1-canary.3613.62584.0</code></summary>
  <br />
  
  :sparkles: Test out this PR locally via:
  
  ```sh
  npm install @artsy/reaction@26.54.1-canary.3613.62584.0
  # or 
  yarn add @artsy/reaction@26.54.1-canary.3613.62584.0
  ```
</details>

### CODE REVIEW

**Comment by damassi** [comment]
Nice @eessex! Much appreciated.

**Comment by eessex** [comment]
Old:
```
npm notice package size:  3.7 MB                                  
npm notice unpacked size: 22.1 MB 
```

New:
```
npm notice package size:  1.2 MB                                  
npm notice unpacked size: 5.7 MB   
```

**Comment by eessex** [comment]
Verified that all is working in Force, this is ready to merge. Related PR: https://github.com/artsy/force/pull/6025

**Comment by damassi** [comment]
🍏

**Comment by artsyit** [comment]
:rocket: PR was released in [`v27.0.0`](https://github.com/artsy/reaction/releases/tag/v27.0.0) :rocket:

**Pull request merged**
