### PR TITLE
Fixes collapsing container

### PR DESCRIPTION
**Pull request by dzucconi**
Re: [FX-1850](https://artsyproduct.atlassian.net/browse/FX-1850)

Simple thing, just ticking a box off my onboarding list here.

### CODE REVIEW

**Comment by damassi** [comment]
@dzucconi - once you assign someone the peril CI check should go away.

**Comment by dzucconi** [comment]
OH, here I am thinking it was asking me to assign a reviewer.

**Comment by damassi** [comment]
The PR flow is generally:
- Assignee is the person responsible for merging / approving 
- Reviewers review, but in some cases can also merge / approve depending on context, etc

**Comment by damassi** [comment]
I think [peril's merge on green](https://github.com/artsy/peril-settings/blob/master/org/mergeOnGreen.ts) functionality is broken but lets see if this works:

#mergeOnGreen

**Comment by artsyit** [comment]
:rocket: PR was released in [`v26.24.2`](https://github.com/artsy/reaction/releases/tag/v26.24.2) :rocket:

**Pull request merged**
