### PR TITLE
[FIX artist] Fix follow artist button

### PR DESCRIPTION
**Pull request by damassi**
Fixes 
- https://artsyproduct.atlassian.net/browse/DISCO-439
- https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&view=planning&selectedIssue=DISCO-437

Also removes a css reset that seemed to be clobbering Force's reset in prod (but not locally) 

Will follow up with a second pr right after with tests. (Want to get this into Force staging.)

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit fcb504da5048da671b59d2f5bb6b1d7dccd7cd7b

https://deploy-preview-1442--artsy-reaction.netlify.com

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 127372d1a2640bb546072baad480b0211f2420b7

https://deploy-preview-1442--artsy-reaction.netlify.com

**Comment by oxaudo** [comment]
Merge on green

**Comment by damassi** [comment]
(Ahh merge on green is down right now)

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 370b9802613a5d8c48cd53d069e6dbdbbd2390c1

https://deploy-preview-1442--artsy-reaction.netlify.com

**Pull request merged**
