### PR TITLE
Increases tap area for tabs

### PR DESCRIPTION
**Pull request by dzucconi**
Not a huge patch here just changes the vertical whitespace surrounding the tab to also be hit area

Just opening it up as draft and will merge this into force once @damassi merges the reaction migration.

### CODE REVIEW

**Comment by damassi** [comment]
Thnx @dzucconi 👍

**Comment by dzucconi** [comment]
@damassi 968911afa184dfb3058bab1d07d22adf099cb554 sneaks in a lil fix for the header height on mobile. I know u mentioned you're moving these PRs over. Happy to do so after reaction is merged into force of course — just ping me and lemme know.

**Comment by damassi** [comment]
Oh yeah any fixes are appreciated 👍 I'm trying to get CI green now (everything is all good locally?) so will report back once thats all done.

**Comment by damassi** [comment]
This code

**Pull request closed without merging**
