### PR TITLE
@damassi => Couple misc search results QA items

### PR DESCRIPTION
**Pull request by mzikherman**
Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-924

Closes https://artsyproduct.atlassian.net/secure/RapidBoard.jspa?rapidView=57&projectKey=DISCO&modal=detail&selectedIssue=DISCO-922

Commits tell the story.

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 0baa5fef3235dd68cdc286a1e21af04898ced89f

https://deploy-preview-2284--artsy-reaction.netlify.com

**Comment by damassi** [comment]
LGTM 👍 

merge on green

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 57cfa708e37cee888e7823a083310f0f99d90738

https://deploy-preview-2284--artsy-reaction.netlify.com

**Comment by artsyit** [comment]
:rocket: PR was released in v15.13.12 :rocket:

**Pull request merged**
