### PR TITLE
@damassi => Move more specs to `renderRelayTree`

### PR DESCRIPTION
**Pull request by mzikherman**
There's only one spec left that uses the stub provider, that's in progress.

### CODE REVIEW

**Comment by damassi** [comment]
Nice! not so bad.

**Comment by artsyit** [comment]
:rocket: PR was released in v21.9.5 :rocket:

**Comment by mzikherman** [comment]
cc @alloy

**Comment by alloy** [comment]
Great, thanks @mzikherman !

**Pull request merged**
