### PR TITLE
Responsive typography sizes

### PR DESCRIPTION
**Pull request by pepopowitz**
WIP because it needs an updated version of palette, based on [PR 125](https://github.com/artsy/palette/pull/125). Once that PR is merged into palette & a new version is cut, the dependency version needs to be bumped here.

This PR includes...

* A change to the TransactionSummary component to use the new [responsive typography sizes of palette](https://github.com/artsy/palette/pull/125).
* An updated version of palette (once that PR is merged ^^^) 
* Updated versions of styled-system & its associated types. Weirdness was happening with older versions of styled-system, where the appropriate media queries weren't always rendering. The updated versions seem to not have that problem.
* Unrelated changes to two components that were specifying invalid values for the `flexwrap` prop. This was causing type-checking to err.

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit d24ee5a4a44f2c5db2cc22b320fa699b3aa1ff35

https://deploy-preview-1531--artsy-reaction.netlify.com

**Comment by zephraph** [comment]
I went ahead and updated palette and the changed snapshots. Did some tests.... it works amazingly well. ❤️This is one awesome PR. 

Thanks for getting it to this point @pepopowitz!

**Comment by alloy** [comment]
This change affects the Buy Now shipping form, where it somehow changes the line-height of the ‘Country’ `div` to `288px`, as can be seen [here](https://deploy-preview-1531--artsy-reaction.netlify.com/?selectedKind=Apps%2FOrder%20Page%2FBuy%20Now%2FShipping&selectedStory=Shipping%20-%20Pre-filled&full=0&addons=1&stories=1&panelRight=0&addonPanel=PeterPanen%2Fstorybook-addon-scissors%2Fpanel) and below.

screen shot 2018-11-11 at 23 04 50

**Comment by alloy** [comment]
And the payment form as well:

screen shot 2018-11-11 at 23 12 02

**Comment by zephraph** [comment]
Hmm... We'd seen a similar issue before `px` coercion was added [here](https://github.com/artsy/palette/pull/125/files#diff-4c2ee7c22068abde2a34740e4de8a6acR14). Is that what's still happening? Is it using `em` instead of `px`?

**Comment by pepopowitz** [comment]
It is definitely rendering it as a line-height of 18em instead of 18px. I'll see if I can figure out why.

**Pull request merged**
