### PR TITLE
[yeoman] Add empty stub so the omakase generator knows what the root is.

### PR DESCRIPTION
**Pull request by alloy**
What the topic said

### CODE REVIEW

**Comment by artsyit** [comment]
Deploy preview for *artsy-reaction* ready!

Built with commit 8ac68939f7c5bf891d9bdf3c148d961480b530dc

https://deploy-preview-1773--artsy-reaction.netlify.com

**Comment by orta** [comment]
Feels hacky, but I'll accept this for pre-1.0 of `om` 👍

**Comment by alloy** [comment]
Yeoman expects that file, which it normally creates when you create an app using yeoman :/

**Comment by orta** [comment]
Weird, it never greened

**Pull request merged**
